# TWITTER_KEY: 'AFZVeMiTNEwYnyi3f7iCg'
# TWITTER_SECRET: 'mZh3D7lJd2N8fA9b3vlPzbi7DY6zlGc7FAZp1Mzm6I'


heroku config:add TWITTER_KEY=AFZVeMiTNEwYnyi3f7iCg TWITTER_SECRET=<mZh3D7lJd2N8fA9b3vlPzbi7DY6zlGc7FAZp1Mzm6I